import OpenAI from "openai";
import { Buffer } from "buffer";

const client = new OpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: process.env.OPENROUTER_API_KEY,
});

export interface GeneratedImageResult {
  success: boolean;
  imageData?: Buffer;
  error?: string;
}

export async function generateImageFromDrawing(
  imageBuffer: Buffer,
  prompt: string,
): Promise<GeneratedImageResult> {
  try {
    // Convert buffer to base64
    const base64Image = imageBuffer.toString("base64");

    console.log("Generating image with prompt:", prompt);

    const response = await client.chat.completions.create({
      model: "google/gemini-2.5-flash-image-preview:free",
      messages: [
        {
          role: "user",
          content: [
            {
              type: "text",
              text: `Generate an image based on this image and prompt31111111111111111111111111111e111111111111111111111111111111: ${prompt}`,
            },
            {
              type: "image_url",
              image_url: {
                url: `data:image/png;base64,${base64Image}`,
              },
            },
          ],
        },
      ],
    });

    if (response.choices && response.choices[0].message) {
      const message = response.choices[0].message;

      // Print any textual content for debugging
      if (message.content) {
        console.log("Gemini text response:", message.content);
        console.log("Message object keys:", Object.keys(message));
        console.log("Full message:", JSON.stringify(message, null, 2));
      }

      // Check if the response content contains an image URL
      if (message.content && typeof message.content === "string") {
        const imageUrlRegex =
          /!\[.*?\]\((https:\/\/.*?\.(?:png|jpg|jpeg|gif|webp))\)/g;
        const matches = message.content.match(imageUrlRegex);

        if (matches && matches.length > 0) {
          const imageUrl = matches[0].match(/\((https:\/\/.*?)\)/)?.[1];
          if (imageUrl) {
            try {
              const response = await fetch(imageUrl);
              const imageBuffer = Buffer.from(await response.arrayBuffer());
              console.log(
                "Downloaded generated image, size:",
                imageBuffer.length,
                "bytes",
              );

              return {
                success: true,
                imageData: imageBuffer,
              };
            } catch (fetchError) {
              console.error("Error downloading generated image:", fetchError);
            }
          }
        }
      }

      // If no images found, return error
      console.log("No images found in Gemini response");
      console.log("Full response object:", JSON.stringify(response, null, 2));
      return {
        success: false,
        error: "No images generated by the model",
      };
    }

    return {
      success: false,
      error: "No response from the model",
    };
  } catch (error) {
    console.error("Error generating image with Gemini:", error);
    return {
      success: false,
      error: `Failed to generate image: ${error instanceof Error ? error.message : "Unknown error"}`,
    };
  }
}
